export const listContinueListeningTypes = {
    PUSH_ARTICLE : 'PUSH_ARTICLE',
    // UPSERT_ARTICLE : 'UPSERT_ARTICLE',
    REMOVE_ARTICLE : 'REMOVE_ARTICLE',
    FETCH_CONTINUE_LISTENING_REQUEST : 'FETCH_CONTINUE_LISTENING_REQUEST',
    FETCH_CONTINUE_LISTENING_SUCCESS : 'FETCH_CONTINUE_LISTENING_SUCCESS',
    LOAD_MORE_CONTINUE_LISTENING_SUCCESS : 'LOAD_MORE_CONTINUE_LISTENING_SUCCESS',
    FETCH_CONTINUE_LISTENING_FAILURE : 'FETCH_CONTINUE_LISTENING_FAILURE',
    UPSERT_CONTINUE_LISTENING_REQUEST : 'UPSERT_CONTINUE_LISTENING_REQUEST',
    UPSERT_CONTINUE_LISTENING_SUCCESS : 'UPSERT_CONTINUE_LISTENING_SUCCESS',
    UPSERT_CONTINUE_LISTENING_FAILURE : 'UPSERT_CONTINUE_LISTENING_FAILURE',
    REMOVE_CONTINUE_LISTENING_REQUEST : 'REMOVE_CONTINUE_LISTENING_REQUEST',
    REMOVE_CONTINUE_LISTENING_SUCCESS : 'REMOVE_CONTINUE_LISTENING_SUCCESS',
    REMOVE_CONTINUE_LISTENING_FAILURE : 'REMOVE_CONTINUE_LISTENING_FAILURE'
}